### ISSUE TITLE
there was a problem running train.py

### ISSUE THREAD

**Issue by ZhangYuanKai123** [hungcn/zalo_hum2song#1]
Excuse me ， I want to know how to get this file
![image](https://user-images.githubusercontent.com/96975259/154246401-8ff531a4-69d9-43ae-9649-921c752455be.png)

**Comment by hungcn** [comment]
Hi @superZYK, you have to download the dataset from ZaloAIChallenge first. You can get it here: https://challenge.zalo.ai/portal/hum-to-song

**Comment by ZhangYuanKai123** [comment]
wa! Thank you,I just want to try to do the task that make hum become a song by machine learning.But I don't know how to do it.Thank you again for sharing again!

**Comment by hungcn** [comment]
> 

I think you're maybe misunderstanding the project, it aims to search (or recommend) songs based on the input hum melody, not generate hum to song

**Comment by ZhangYuanKai123** [comment]
Yes,but I have already found the solution for the question!Thank you!!!
